codecov:
  notify:
    wait_for_ci: no

coverage:
  status:
    patch:
      default:
        target: 60%
        threshold: 5%
    project:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "files"
  require_changes: "coverage_drop OR uncovered_patch"
