codecov:
  notify:
    wait_for_ci: no

coverage:
  status:
    patch: false
    project:
      default:
        target: 90%
        threshold: 2%

comment:
  layout: "files"
  require_changes: "coverage_drop OR uncovered_patch"
